### ISSUE TITLE
Doesn't seem to work with Linux Mint

### ISSUE THREAD

**Issue by id-petrov** [martingeorg/tmpfs-mysql#5]
the server fails to start when using Linux  mint ,the log doesn't show why

**Comment by martingeorg** [comment]
Hi @diG1tY, i've tested with the last two Linux Mint releases. On those installations it works at once. Those however were fresh installs. Could you provide the tmpfsmysql.log file so i could check for any clues as to why it fails to start.

**Comment by martingeorg** [comment]
I'm closing the issue as things run fine when testing with Vagrant boxes and i can't get more information about possible reasons as to why it fails.
